######################################################################
# Automatically generated by qmake (3.0) Wed Jan 13 11:39:41 2016
######################################################################

TEMPLATE = app
TARGET = Adder
INCLUDEPATH += .
QT += widgets
# Input
HEADERS += Adder.h
SOURCES += Adder.cpp Window.cpp
