######################################################################
# Automatically generated by qmake (3.0) Wed Jan 13 13:57:49 2016
######################################################################

TEMPLATE = app
TARGET = Easter
INCLUDEPATH += .
QT += widgets
# Input
HEADERS += Easter.h
SOURCES += Easter.cpp Window.cpp
